// angular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Global } from '../../services/global';
import Swal from 'sweetalert2';

@Component({
	selector: 'appArticle',
	templateUrl: './article.component.html',
	styleUrl: './article.component.css',
	providers: [ArticleService]
})

export class ArticleComponent implements OnInit{
	public homeText: string;
	public article = {_id: '',     title: '',     content: '',     image: '',     date: ''};
	public URLTemplate:string;
	
	constructor(
		private _articleService: ArticleService,
		private _route: ActivatedRoute,
		private _router: Router
	){
		this.homeText = 'Blog';
		this.URLTemplate = Global.url;
	}

	ngOnInit(): void {

		this._route.params.subscribe(params => {
			let articleId = params['id'];
			this._articleService.getArticle(articleId).subscribe({
				next: response => {
					if(response.article){
						this.article = response.article;
					} else {
						this._router.navigate(['/home']);
					}
				},
				error: error => {
					console.log("error",error);
					this._router.navigate(['/home']);
				}
			});
		})

	}

	deleteArticle(id:string){
		Swal.fire({
			title: "Are you sure?",
			text: "You won't be able to revert this!",
			icon: "warning",
			showCancelButton: true,
			confirmButtonColor: "#3085d6",
			cancelButtonColor: "#d33",
			confirmButtonText: "Yes, delete it!"
		  }).then((result) => {
			if (result.isConfirmed) {
				this._articleService.deleteArticle(id).subscribe({
					next: response => {
						Swal.fire({
							title: "Deleted!",
							text: "Your article has been deleted.",
							icon: "success"
						  });
						this._router.navigate(['/blog']);
					},
					error: error => {
						console.log("error",error);
						this._router.navigate(['/blog/article/', this.article._id]);
					}
				});
			}
		  });
	}

}

<div class="center">
    <section id="content">
        <article class="articleItem articleDetail">
            <div class="imageWrap">
                <img src="{{URLTemplate + 'image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
                <img src="https://placehold.co/1000x400" alt="{{article.title}}" *ngIf="!article.image">
            </div>

            <h2 class="subHeader">
                {{article.title}}
            </h2>
            <span class="date">
                {{article.date | amLocale: 'en' | amTimeAgo}}
            </span>
            <p>
                {{article.content}}
            </p>

            <div class="buttons">
                <a [routerLink]="['/article/edit', article._id]" class="btnSmall btnWarning">Edit</a>
                <a (click)="deleteArticle(article._id)" class="btnSmall btnDanger">Delete</a>
            </div>

            <div class="clearfix"></div>
        </article>
    </section>

    <appSidebar></appSidebar>
</div>

// reactmaster/src/components/Article.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import { NavLink, useNavigate, useParams } from "react-router-dom";
import Global from "../Global";
import Moment from "react-moment";
import Swal from 'sweetalert2'

const Article = () => {
    const articleID = useParams().id;  
    const [article, setArticle] = useState({});
    const navigate = useNavigate();

    useEffect(()=>{
        const getArticle = () => {
            axios
                .get(Global.url+"article/"+articleID)
                .then((response) => {
                    setArticle(response.data.article);
                })
                .catch((error) =>{
                    console.log(error + "Cannot get the article");
                    setArticle({});
                });
        };

        getArticle(articleID);
    }, [articleID, navigate]);

    useEffect(() => {
        setArticle({});
    }, [articleID]);

    const handleDelete = (id) => {
        Swal.fire({
          title: "Confirmation",
          text: "Are you sure you want to delete this article?",
          icon: "warning",
          showCancelButton: true,
          confirmButtonText: "Yes, delete it",
          cancelButtonText: "Cancel",
        }).then((result) => {
          if (result.isConfirmed) {
            axios
              .delete(Global.url + "article/" + id)
              .then(() => {
                Swal.fire({
                  title: "Success",
                  text: "Article deleted successfully",
                  icon: "success",
                  confirmButtonText: "OK",
                }).then(() => {
                  navigate("/blog");
                });
              })
              .catch((error) => {
                console.log(error + "Cannot delete the article");
                navigate("/edit/" + id);
              });
          }
        });
      };

    if(Object.keys(article).length > 0){
        let articleEditURL = "/article/edit/"+article._id;
        return (
            <section id="content">
                <article className="articleItem articleDetail">
                    <div className="imageWrap">
                        {article.image !== null ? (
                            <img
                                src={Global.url + "image/" + article.image}
                                alt={article.title}
                            />
                        ) : (
                            <img
                                src="https://placehold.co/1000x400"
                                alt={article.title}
                            />
                        )}
                    </div>
                    <h1 className="subHeader">{article.title}</h1>
                    <span className="date">
                        <Moment fromNow>{article.date}</Moment>
                    </span>
                    <p>{article.content}</p>

                    <div className="buttons">
                        <NavLink to={articleEditURL} className={() => ['btnSmall', 'btnWarning'].join(" ")} end>Edit</NavLink>
                        <button className="btnSmall btnDanger" onClick={() => handleDelete(article._id)}>Delete</button>
                    </div>
                    <div className="clearfix"></div>
                </article>
            </section>
        );
    } else {
        return (
            <section id="content">
                <article className="articleItem articleDetail">
                    <h2 className="subHeader" style={{ textAlign: "center" }}>El articulo no existe</h2>
                </article>
            </section>
        );
    }
}

export default Article;
