// vuemaster/src/components/templates/ErrorComponent.vue
<template>
	<div id="content" className="error404">
		<div className="errorImage">
			<img src="../../assets/images/404error.png" alt="404Error" />
		</div>
		<div>
			<h1 className="subHeader">404 Page Not Found</h1>
			<p>
				The page you are looking for doesn't exists, please try again
				later
			</p>
		</div>
	</div>
</template>

<script>
export default {
	name: "ErrorComponent"
};
</script>

// reactmaster/src/components/ErrorComponent.jsx
import React, { Component } from "react";
import errorImage from '../assets/images/404error.png'

class ErrorComponent extends Component {
	render() {
		return (
			<div id="content" className="Error404">
				<div className="errorImage">
					<img src={errorImage} alt="404Error" />
				</div>
				<div>
					<h1 className="subHeader">404 Page Not Found</h1>
					<p>
						The page you are looking for doesn't exists, please try
						again later
					</p>
				</div>
			</div>
		);
	}
}

export default ErrorComponent;
