// vuemaster/src/components/templates/HeaderComponent.vue
<template>
	<header id="header">
		<div class="center">
			<!--logo-->
			<div id="logo">
				<img src="../../assets/images/vue.svg" alt="appLogo"/>
				<span id="brand"> <strong>Curso</strong>Vue </span>
			</div>

			<!--Nav-->
			<nav id="menu">
				<ul>
					<li>
						<router-link active-class="active" to="/">Home</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/blog">Blog</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/form">Form</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/movies">Movies</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/testpage">Test</router-link>
					</li>
				</ul>
			</nav>

			<div class="clearfix"></div>
		</div>
	</header>
</template>

<script>
export default {
    name: 'HeaderComponent'
}
</script>

// reactmaster/src/components/Header.jsx
import React, { Component } from "react";
import logo from "../assets/images/logo.svg";
import { NavLink  } from "react-router-dom";

class Header extends Component {
	render() {
		return (
			<header id="header">
				<div className="center">
					<div id="logo">
						<img src={logo} alt="appLogo" />
						<span id="brand">
							<strong>Curso</strong>React
						</span>
					</div>
					<nav id="menu">
						<ul>
							<li>
								<NavLink to="/">Home</NavLink>
							</li>
							<li>
								<NavLink to="/blog">Blog</NavLink>
							</li>
							<li>
								<NavLink to="/form">Form</NavLink>
							</li>
							<li>
								<NavLink to="/movies">Movies</NavLink>
							</li>
							<li>
								<NavLink to="/testpage">Page</NavLink>
							</li>
						</ul>
					</nav>
					<div className="clearfix"></div>
				</div>
			</header>
		);
	}
}

export default Header;
