// angular/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
	selector: 'appSidebar',
	templateUrl: './sidebar.component.html',
	styleUrl: './sidebar.component.css'
})
export class SidebarComponent {
	public searchString: string;

    constructor (
		private _router: Router,
		private _route: ActivatedRoute
	) {
		this.searchString = '';
    }

    onSubmit(){
		this._router.navigate(['/search',this.searchString])
  	}

}

<aside id="sidebar">
    <div id="navBlog" class="sidebarItem">
        <h3>You can</h3>
        <a [routerLink]="['/article/create']" class="btn btnSuccess">Create Article</a>
    </div>
    <div id="search" class="sidebarItem">
        <h3>Searcher</h3>
        <p>Search the article you are looking for</p>
        <form #searchForm="ngForm" (ngSubmit)="onSubmit()">
            <input type="text" name="search" #search="ngModel" [(ngModel)]="searchString" required>

            <input type="submit" name="submit" value="Search" class="btn">
        </form>
    </div>
</aside>

<div class="clearfix"></div>

// reactmaster/src/components/Sidebar.jsx
import React, { Component } from "react";

class Sidebar extends Component {
	render() {
		return (
			<aside id="sidebar">
				<div id="navBlog" className="sidebarItem">
					<h3>You can</h3>
					<p href="#" className="btn btnSuccess">
						Create Article
					</p>
				</div>
				<div id="search" className="sidebarItem">
					<h3>Searcher</h3>
					<p>Search the article you are looking for</p>
					<form>
						<input type="text" name="search" />
						<input
							type="submit"
							name="submit"
							value="Search"
							className="btn"
						/>
					</form>
				</div>
			</aside>
		);
	}
}

export default Sidebar;
