// reactmaster/src/components/Movie.jsx
import React, { Component } from "react";

class Movie extends Component {
    
    mark = () => {
        this.props.markFavorite(this.props.movie, this.props.index);
    }
    
    render(){
        const {title, image} = this.props.movie

        return(
            <article className="articleItem">
                <div className="imageWrap">
                    <img src={image} alt={title} />
                </div>

                <h2>{title}</h2>
                <span className="date">
                    5 minutes ago
                </span>
                <p>Read More</p>
                <button onClick={this.mark}>Mark as Favorite</button>
                <div className="clearfix"></div>
            </article>
        )
    }

}

export default Movie;

// angular/src/app/components/movie/movie.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Movie } from '../../models/movie';

@Component({
  selector: 'appMovie',
  templateUrl: './movie.component.html',
  styleUrl: './movie.component.css'
})

export class MovieComponent {

  @Input() movie!: Movie;
  @Input() index:number=0;

  @Output() markFavorite = new EventEmitter();

  constructor(){
  }

  selectFavorite(event: Event,movie: Movie){
    this.markFavorite.emit({
      movie: movie
    });
  }

}

<article class="articleItem">
    <div class="imageWrap">
        <img src="{{movie.image}}" alt="{{movie.title}}">
    </div>

    <h2>{{movie.title}}</h2>
    <span class="date">
        5 minutes ago
    </span>
    <span class="year" [ngClass]="{
        'yearGreen' : movie.year > 2016,
        'yearRed' : movie.year < 2016
    }">
        {{movie.year}}
    </span>
    <a href="#">Read More</a>

    <button (click)="selectFavorite($event,movie)">Select as Favorite</button>
    <div class="clearfix"></div>
</article>
