// angular/src/app/components/form/form.component.ts
import { Component } from '@angular/core';

@Component({
  	selector: 'appForm',
  	templateUrl: './form.component.html',
  	styleUrl: './form.component.css',
})

export class FormComponent {
  	public homeText = 'Form';
  	public user: any;
	public field: string;

  	constructor() {
		this.field = '';
		this.user = {
			firstname: '',
			lastname: '',
			bio: '',
			gender: '',
		};
  	}

	onSubmit(){
		console.log(this.user);
  	}

	clickedButton(){
		console.log('Clicked Button');
	}

	hasExit(){
		console.log('Has exit the input');
	}

}

<appSlider [pageTitle]="homeText" [size]="'small'"></appSlider>

<div class="center">
    <section id="content">
        <form class="midForm" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="formGroup">
                <label for="firstname">First Name</label>
                <input type="text" name="firstname" #firstname="ngModel" [(ngModel)]="user.firstname" required pattern="[a-zA-z]+">

                <small *ngIf="!firstname.valid && firstname.touched">
                    The First Name is not valid
                </small>
            </div>

            <div class="formGroup">
                <label for="lastname">Last Name</label>
                <input type="text" name="lastname" #lastname="ngModel" [(ngModel)]="user.lastname" required pattern="[a-zA-z]+">

                <small *ngIf="!lastname.valid && lastname.touched">
                    The Last Name is not valid
                </small>
            </div>

            <div class="formGroup">
                <label for="bio">Bio</label>
                <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>

                <small *ngIf="!bio.valid && bio.touched">
                    The Bio is not valid
                </small>
            </div>

            <div class="formGroup radioButtons">
                <input type="radio" name="gender" value="male" #gender="ngModel" [(ngModel)]="user.gender" required/>Male
                <input type="radio" name="gender" value="female" #gender="ngModel" [(ngModel)]="user.gender" required/>Female
                <input type="radio" name="gender" value="other" #gender="ngModel" [(ngModel)]="user.gender" required/>Other

                <small *ngIf="!gender.valid && gender.touched">
                    The Gender is not valid
                </small>
            </div>
            <div class="clearfix"></div>

            <input type="submit" value="Submit" class="btn btnSuccess" [disabled]="userForm.invalid">
        </form>

        <h2 class="subHeader">Eventos</h2>
        <button (click)="clickedButton()"></button>

        <input type="text" [(ngModel)]="field" (blur)="hasExit()">
        {{field}}
    </section>

    <appSidebar></appSidebar>
</div>

// vuemaster/src/components/views/FormComponent.vue
<template>
	<SliderComponent />
	<div class="center">
		<section id="content">
			<h1 class="subHeader">{{ pageSubtitle }}</h1>
			<Form class="midForm" @submit="submitUserForm">
				<div class="formGroup">
					<label for="firstname">First Name:</label>
					<Field
						name="firstname"
						id="firstname"
						as="input"
						rules="required|min:3"
						type="text"
					/>
					<ErrorMessage name="firstname" as="p">
						The First Name cannot be empty and need to have more
						than 3 characters
					</ErrorMessage>
				</div>

				<div class="formGroup">
					<label for="lastname">Last Name:</label>
					<Field
						name="lastname"
						id="lastname"
						as="input"
						rules="required|min:3"
						type="text"
					/>
					<ErrorMessage name="lastname" as="p" />
				</div>

				<div class="formGroup">
					<label for="lastname">Bio:</label>
					<Field
						name="bio"
						id="bio"
						as="textarea"
						rules="required|min:10"
					/>
					<ErrorMessage name="bio" as="p" />
				</div>

				<div class="formGroup radioButtons">
					<Field
						name="gender"
						type="radio"
						value="male"
						rules="required"
					/>
					Male
					<Field
						name="gender"
						type="radio"
						value="female"
						rules="required"
					/>
					Female
					<Field
						name="gender"
						type="radio"
						value="other"
						rules="required"
					/>
					Other
					<br />
					<ErrorMessage name="gender" as="p" />
				</div>
				<div class="clearfix"></div>

				<input
					type="submit"
					value="Submit"
					class="btn btnSuccess"
					@click="validate"
				/>
			</Form>
		</section>
		<SidebarComponent />
	</div>
</template>

<script>
import SliderComponent from "../templates/SliderComponent.vue";
import SidebarComponent from "../templates/SidebarComponent.vue";
import { Form, Field, ErrorMessage, defineRule } from "vee-validate";

defineRule("required", (value) => {
	if (!value || !value.length) {
		return "This field is required";
	}
	return true;
});

defineRule("min", (value, [limit]) => {
	if (!value || !value.length) {
		return true;
	}
	if (value.length < limit) {
		return `This field must be at least ${limit} characters`;
	}
	return true;
});

export default {
	name: "FormComponent",
	components: {
		SliderComponent,
		SidebarComponent,
		Form,
		Field,
		ErrorMessage,
	},
	data() {
		return {
			pageSubtitle: "Form",
		};
	},
	methods: {
		submitUserForm(values) {
			console.log(values);
		},
	},
};
</script>
