// angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'appHeader',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}

<header id="header">
    <div class="center">
        <!--logo-->
        <div id="logo">
            <img src="assets/images/angular.svg" alt="appLogo" alt="Logo">
            <span id="brand">
                <strong>Curso</strong>Angular
            </span>
        </div>

        <!--Nav-->
        <nav id="menu">
            <ul>
                <li>
                    <a [routerLink]="['/home']" [routerLinkActive]="['active']">Home</a>
                </li>
                <li>
                    <a [routerLink]="['/blog']" [routerLinkActive]="['active']">Blog</a>
                </li>
                <li>
                    <a [routerLink]="['/form']" [routerLinkActive]="['active']">Form</a>
                </li>
                <li>
                    <a [routerLink]="['/movies']" [routerLinkActive]="['active']">Movies</a>
                </li>
                <li>
                    <a [routerLink]="['/testpage']" [routerLinkActive]="['active']">Test</a>
                </li>
            </ul>
        </nav>

        <div class="clearfix"></div>
    </div>
</header>

// vuemaster/src/components/templates/HeaderComponent.vue
<template>
	<header id="header">
		<div class="center">
			<!--logo-->
			<div id="logo">
				<img src="../../assets/images/vue.svg" alt="appLogo"/>
				<span id="brand"> <strong>Curso</strong>Vue </span>
			</div>

			<!--Nav-->
			<nav id="menu">
				<ul>
					<li>
						<router-link active-class="active" to="/">Home</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/blog">Blog</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/form">Form</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/movies">Movies</router-link>
					</li>
					<li>
						<router-link active-class="active" to="/testpage">Test</router-link>
					</li>
				</ul>
			</nav>

			<div class="clearfix"></div>
		</div>
	</header>
</template>

<script>
export default {
    name: 'HeaderComponent'
}
</script>
