// reactmaster/src/components/ErrorComponent.jsx
import React, { Component } from "react";
import errorImage from '../assets/images/404error.png'

class ErrorComponent extends Component {
	render() {
		return (
			<div id="content" className="Error404">
				<div className="errorImage">
					<img src={errorImage} alt="404Error" />
				</div>
				<div>
					<h1 className="subHeader">404 Page Not Found</h1>
					<p>
						The page you are looking for doesn't exists, please try
						again later
					</p>
				</div>
			</div>
		);
	}
}

export default ErrorComponent;

// angular/src/app/components/error/error.component.ts
import { Component, Input } from '@angular/core';

@Component({
	selector: 'appError',
	templateUrl: './error.component.html',
	styleUrl: './error.component.css'
})
export class ErrorComponent {
	@Input() typeError: string;
	@Input() errorTitle: string;
	@Input() errorContent: string;

	constructor(){
		this.typeError = 'default';
		this.errorTitle = '';
		this.errorContent = '';
	}
}

<div [ngClass]="{
    'errorImage' : typeError == 'default',
    'errorImageSmall' : typeError == 'searchError' || typeError == 'customError'
}">
    <img src="assets/images/404error.png" alt="appNotFound" alt="404Error">
</div>

<div *ngIf="typeError == 'default'">
    <h1 class="subHeader">404 Page Not Found</h1>
    <p>The page you are looking for doesn't exists, please try again later</p>
</div>

<div *ngIf="typeError == 'searchError'">
    <h1 class="subHeader">No articles Found</h1>
    <p>Please try using diferent search words</p>
</div>

<div *ngIf="typeError == 'customError'">
    <h1 class="subHeader">{{errorTitle}}</h1>
    <p>{{errorContent}}</p>
</div>
